# Generated by Django 3.1.2 on 2020-10-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
    ]
